export const TILES_TYPES = {
  VOID: "void",
  GRASS_1: "grass_1",
  GRASS_2: "grass_2",
  GRASS_3: "grass_3",
  GRASS_4: "grass_4",
  GRASS_5: "grass_5",

  FLOWERS_1: "flowers_1",
  FLOWERS_2: "flowers_2",

  CRATE_1_OPENED: "crate_1_opened",
  CRATE_1_CLOSED: "crate_1_closed",

  GROUND_BOTTOM: "ground_bottom",
  GROUND_BOTTOM_LEFT: "ground_bottom_left",
  GROUND_BOTTOM_RIGHT: "ground_bottom_right",
  GROUND_TOP_LEFT: "ground_top_left",
  GROUND_TOP_RIGHT: "ground_top_right",
  GROUND_TOP: "ground_top",
  GROUND_MIDDLE: "ground_middle",
  GROUND_MIDDLE_LEFT: "ground_middle_left",
  GROUND_MIDDLE_RIGHT: "ground_middle_right",
  GROUND_CROSS: "ground_cross",
  GROUND_CORNER_BOTTOM_LEFT: "ground_corner_bottom_left",
  GROUND_CORNER_BOTTOM_RIGHT: "ground_corner_bottom_right",
  GROUND_CORNER_TOP_LEFT: "ground_corner_top_left",
  GROUND_CORNER_TOP_RIGHT: "ground_corner_top_right",
  GROUND_CORNERS_LEFT: "ground_corners_left",
  GROUND_CORNERS_RIGHT: "ground_corners_right",
  GROUND_CORNERS_TOP: "ground_corners_top",
  GROUND_CORNERS_BOTTOM: "ground_corners_bottom",

  //HOUSE
  ROOF_1: "roof_1",
  ROOF_2: "roof_2",
  WALL_1: "wall_1",
  WALL_2: "wall_2",
  WALL_3: "wall_3",
  WINDOW_1: "window_1",
  FLOOR_1: "floor_1",
  FLOOR_1_EXIT: "floor_1_exit",
  FLOOR_2: "floor_2",
  FLOOR_2_EXIT: "floor_2_exit",
  RUG_1: "rug_1",
  RUG_2: "rug_2",
  RUG_3: "rug_3",
  RUG_4: "rug_4",
  RUG_5: "rug_5",
  RUG_6: "rug_6",
  RUG_7: "rug_7",
  RUG_8: "rug_8",
  RUG_9: "rug_9",
  INDOOR_WALL_1: "indoor_wall_1",
  INDOOR_ROOF_1: "indoor_roof_1",
  INDOOR_ROOF_2: "indoor_roof_2",
  INDOOR_ROOF_3: "indoor_roof_3",
  CHIMNEY_1: "chimney_1",
  CHIMNEY_2: "chimney_2",
  INDOOR_WINDOW_1: "indoor_window_1",
  INDOOR_WINDOW_2: "indoor_window_2",
  BED_1: "bed_1",
  BED_2: "bed_2",
  SHELF: "shelf",

  //MISC
  DOOR_1: "door_1",
  LOGS_1: "logs_1",
  PATH_1: "path_1",
  SIGN_1: "sign_1",
  WATER_TANK: "water_tank",
  WELL: "well",
  STONE: "stone",
  WATER: "water",

  TENT_1: "tent_1",
  TENT_2: "tent_2",
  TENT_3: "tent_3",
  TENT_4: "tent_4",
  TENT_5: "tent_5",
  TENT_6: "tent_6",
  TENT_7: "tent_7",
  TENT_8: "tent_8",
  TENT_9: "tent_9",

  TREE_1: "tree_1",
  TREE_2: "tree_2",
  TREE_3: "tree_3",
  TREE_4: "tree_4",
  TRUNK_1: "trunk_1",
  TRUNK_2: "trunk_2",
};
